version: "3.7"

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: social_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - social_app_db:/var/lib/postgresql/data

volumes:
  social_app_db: