version: '3.7'

services:
  # postgres:
  #   image: postgres:13.0-alpine
  #   environment:
  #     POSTGRES_DB: social_app
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - '5432:5432'
  #   restart: 'always'
  #   volumes:
  #     - social_app_db:/var/lib/postgresql/data

  postgres2:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: social_app2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: 'always'
    volumes:
      - social_app_2_db:/var/lib/postgresql/data

  # postgres3:
  #   image: postgres:13.0-alpine
  #   environment:
  #     POSTGRES_DB: social_app3
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - '5432:5432'
  #   restart: 'always'
  #   volumes:
  #     - social_app_3_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

volumes:
  social_app_db:
  social_app_2_db:
  social_app_3_db:
